name: build

on: [push, pull_request]

jobs:
  build:
    name: build (${{ matrix.ruby }} / ${{ matrix.os }})
    strategy:
      matrix:
        ruby: [ head ]
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: git config
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
        git config --global advice.detachedHead 0
    - uses: actions/checkout@v2

    - name: Install libraries
      run: sudo apt-get install -q libedit-dev libedit2
      if: startsWith(matrix.os, 'ubuntu')
    - name: Install libraries
      run: brew install libedit
      if: startsWith(matrix.os, 'macos')
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
      if: "!startsWith(matrix.os, 'windows')"

    - name: Set up Ruby
      uses: MSP-Greg/setup-ruby-pkgs@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        mingw: _upgrade_ readline
      if: startsWith(matrix.os, 'windows')

    - name: Set up Bundler
      run: gem install bundler --no-document
    - name: Install dependencies
      run: bundle install
    - name: Run test
      run: rake compile test
    - name: Run test with libedit enabled
      run: rake clobber compile test -- --enable-libedit
      if: "!startsWith(matrix.os, 'windows')"
    - name: Run test with libedit disabled
      run: rake clobber compile test -- --disable-libedit
